security:
    encoders:
        App\Entity\User:
            algorithm: auto


    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: app_user_provider
            form_login: 
                login_path: oauth_login
            guard:
                authenticators:
                    - App\Security\KeycloakAuthenticator
            logout: 
                path: logout

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }

