on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2
      
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: node24-eu.n0c.com
          server-dir: /public_html/
          username:  carl@mediatek86-formation.go.yj.fr
          password: ${{ secrets.ftp_password }}
